import { describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, open, readFile, symlink, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { LibraryEntry, LibraryFileOperations } from "../cli/artifacts";
import { withRecoveredOutputLibrary, writeTranscriptOnlyOutputs } from "../output/output-writer";
import type { Transcript } from "../transcript/transcript-source";
import type { TranscriptQuality } from "../transcript/transcript-quality";
import {
  createArtifactLibraryPort,
  createDefaultTuiSession,
  normalizeArtifactLibraryPath,
} from "./default-ports";

const video = {
  canonicalUrl: "https://www.youtube.com/watch?v=abc123_DEF4",
  videoId: "abc123_DEF4",
} as const;

const transcript: Transcript = {
  language: "en",
  provenance: { isAutoGenerated: false },
  schemaVersion: "transcript.v0",
  segments: [{ duration: 2, start: 0, text: "Useful words." }],
  source: "youtube-transcript-api",
  videoId: video.videoId,
};

const quality: TranscriptQuality = {
  averageCharsPerMinute: 390,
  durationSeconds: 2,
  language: "en",
  qualitySchemaVersion: "transcript-quality.v0",
  segmentCount: 1,
  status: "usable",
  totalTextLength: 13,
  warnings: [],
};

function entry(root: string): LibraryEntry {
  return {
    channel: null,
    paths: {
      digestPath: null,
      emailPreviewPath: null,
      metadataPath: join(root, "metadata", `${video.videoId}.json`),
      transcriptJsonPath: join(root, "transcripts", `${video.videoId}.json`),
      transcriptMarkdownPath: join(root, "transcripts", `${video.videoId}.md`),
      transcriptTextPath: join(root, "transcripts", `${video.videoId}.txt`),
    },
    title: null,
    updatedAt: "2026-06-22T10:00:00.000Z",
    videoId: video.videoId,
  };
}

describe("default TUI ports", () => {
  test("normalizes only exact home shorthands and absolute paths without consulting cwd", () => {
    const home = "/Users/isolated";
    expect(normalizeArtifactLibraryPath("~", home)).toBe(home);
    expect(normalizeArtifactLibraryPath("~/Documents/Video Digest", home))
      .toBe("/Users/isolated/Documents/Video Digest");
    expect(normalizeArtifactLibraryPath("/Volumes/Library/../Video Digest", home))
      .toBe("/Volumes/Video Digest");
    expect(() => normalizeArtifactLibraryPath("~other/Library", home)).toThrow("unsupported home shorthand");
    expect(() => normalizeArtifactLibraryPath("relative/library", home)).toThrow("absolute path");
    expect(() => normalizeArtifactLibraryPath("", home)).toThrow("absolute path");
  });

  test("initializes without network access and resolves the Artifact Library again after saving config", async () => {
    const roots: string[] = [];
    let metadataSources = 0;
    let saved: unknown;
    const session = await createDefaultTuiSession({ print: async () => undefined, quit: () => undefined }, {
      appPaths: {
        configPath: "/app/config.json",
        defaultArtifactLibrary: "/default/library",
        runtimeDir: "/app/runtime",
      },
      configStore: {
        load: async () => null,
        save: async (value) => { saved = value; },
      },
      credentialStore: {
        deleteOpenCodeApiKey: async () => undefined,
        getOpenCodeApiKey: async () => null,
        setOpenCodeApiKey: async () => undefined,
      },
      env: {},
      homeDir: "/Users/isolated",
      libraryFactory: (getOutputDir) => ({
        list: async () => { roots.push(getOutputDir()); return []; },
        open: async () => undefined,
        read: async () => ({ content: "", displayPath: "", title: "" }),
        reveal: async () => undefined,
      }),
      metadataSourceFactory: () => { metadataSources += 1; return { fetch: async () => ({ channel: null, title: null }) }; },
      runtimeManager: {
        inspect: async () => { throw new Error("private runtime detail"); },
        prepare: async () => undefined,
      },
    });

    expect(session.model).toMatchObject({
      config: { artifactLibrary: null, defaultArtifactLibrary: "/default/library" },
      credentialConfigured: false,
      runtimeReadiness: { status: "missing" },
      screen: "choose-library",
    });
    expect(metadataSources).toBe(0);

    expect(await session.ports.config.saveArtifactLibrary("~/Library")).toBe("/Users/isolated/Library");
    await session.ports.library.list();
    expect(saved).toEqual({
      artifactLibrary: "/Users/isolated/Library",
      digest: { defaultProvider: "opencode", models: {} },
      schemaVersion: "config.v1",
    });
    expect(roots).toEqual(["/Users/isolated/Library"]);
  });

  test("creates metadata source only for an explicit operation and resolves the result entry from the Library", async () => {
    let metadataSources = 0;
    let resolvedUnderLock = false;
    const canonical = entry("/library");
    const session = await createDefaultTuiSession({ print: async () => undefined, quit: () => undefined }, {
      appPaths: { configPath: "/app/config.json", defaultArtifactLibrary: "/default", runtimeDir: "/runtime" },
      configStore: {
        load: async () => ({ artifactLibrary: "/library", digest: { defaultProvider: "opencode", models: {} }, schemaVersion: "config.v1" }),
        save: async () => undefined,
      },
      credentialStore: {
        deleteOpenCodeApiKey: async () => undefined,
        getOpenCodeApiKey: async () => null,
        setOpenCodeApiKey: async () => undefined,
      },
      env: {},
      metadataSourceFactory: () => {
        metadataSources += 1;
        return { fetch: async () => ({ channel: null, title: null }) };
      },
      resolveCreatedEntry: async (root, videoId) => {
        expect(root).toBe("/library");
        expect(videoId).toBe(video.videoId);
        resolvedUnderLock = true;
        return canonical;
      },
      runtimeManager: { inspect: async () => ({ status: "ready" }), prepare: async () => undefined },
      transcript: async (input) => ({
        cleanText: "Useful words.\n",
        exitCode: 0,
        paths: {
          metadataPath: "/untrusted/metadata.json",
          transcriptJsonPath: "/untrusted/transcript.json",
          transcriptMarkdownPath: "/untrusted/transcript.md",
          transcriptTextPath: "/untrusted/transcript.txt",
        },
        status: "completed",
        transcriptQuality: quality,
      }),
      withRecoveredLibrary: async (_root, operation) => operation(),
    });

    const result = await session.ports.create.transcript(video.canonicalUrl, {
      onProgress: () => undefined,
      signal: new AbortController().signal,
    });

    expect(metadataSources).toBe(1);
    expect(resolvedUnderLock).toBe(true);
    expect(result).toEqual({ cleanText: "Useful words.\n", entry: canonical, kind: "transcript" });
    expect(JSON.stringify(result)).not.toContain("/untrusted/");
  });

  test("resolves, revalidates, and reads a Library target under one recovery lock", async () => {
    const root = await mkdtemp(join(tmpdir(), "video-digest-tui-library-"));
    await writeTranscriptOnlyOutputs({ outputDir: root, transcript, transcriptQuality: quality, video });
    const port = createArtifactLibraryPort({
      getOutputDir: () => root,
      systemActions: { copy: async () => undefined, open: async () => undefined, reveal: async () => undefined },
    });

    const result = await port.read({ preference: "transcript", videoId: video.videoId });

    expect(result.content).toContain("# Transcript");
    expect(result.displayPath).toBe(`transcripts/${video.videoId}.md`);
    expect(result.title).toBe(video.videoId);
  });

  test("holds the Library lock through open and reveal actions", async () => {
    const root = await mkdtemp(join(tmpdir(), "video-digest-tui-open-lock-"));
    await writeTranscriptOnlyOutputs({ outputDir: root, transcript, transcriptQuality: quality, video });
    const calls: string[] = [];
    const verifyLock = async (kind: string, path: string) => {
      calls.push(`${kind}:${path}`);
      await expect(withRecoveredOutputLibrary(root, async () => undefined)).rejects.toMatchObject({ code: "already-running" });
    };
    const port = createArtifactLibraryPort({
      getOutputDir: () => root,
      systemActions: {
        copy: async () => undefined,
        open: (path) => verifyLock("open", path),
        reveal: (path) => verifyLock("reveal", path),
      },
    });

    const target = { preference: "transcript", videoId: video.videoId } as const;
    await port.open(target);
    await port.reveal(target);

    expect(calls).toEqual([
      `open:${join(root, "transcripts", `${video.videoId}.md`)}`,
      `reveal:${join(root, "transcripts", `${video.videoId}.md`)}`,
    ]);
  });

  test("refuses a symlink swap before read and preserves the external victim", async () => {
    const root = await mkdtemp(join(tmpdir(), "video-digest-tui-swap-"));
    await writeTranscriptOnlyOutputs({ outputDir: root, transcript, transcriptQuality: quality, video });
    const artifact = join(root, "transcripts", `${video.videoId}.md`);
    const victim = join(await mkdtemp(join(tmpdir(), "video-digest-victim-")), "victim.md");
    await writeFile(victim, "external victim");
    let swapped = false;
    const operations: Partial<LibraryFileOperations> = {
      open: async (path, flags) => {
        if (path === artifact && !swapped) {
          swapped = true;
          await unlink(artifact);
          await symlink(victim, artifact);
        }
        return open(path, flags);
      },
    };
    const port = createArtifactLibraryPort({
      fileOperations: operations,
      getOutputDir: () => root,
      systemActions: { copy: async () => undefined, open: async () => undefined, reveal: async () => undefined },
    });

    await expect(port.read({ preference: "transcript", videoId: video.videoId })).rejects.toThrow();
    expect(await readFile(victim, "utf8")).toBe("external victim");
  });

  test("refuses a symlink swap before system open", async () => {
    const root = await mkdtemp(join(tmpdir(), "video-digest-tui-open-swap-"));
    await writeTranscriptOnlyOutputs({ outputDir: root, transcript, transcriptQuality: quality, video });
    const artifact = join(root, "transcripts", `${video.videoId}.md`);
    const victim = join(await mkdtemp(join(tmpdir(), "video-digest-open-victim-")), "victim.md");
    await writeFile(victim, "external victim");
    let swapped = false;
    let opens = 0;
    const port = createArtifactLibraryPort({
      fileOperations: {
        open: async (path, flags) => {
          if (path === artifact && !swapped) {
            swapped = true;
            await unlink(artifact);
            await symlink(victim, artifact);
          }
          return open(path, flags);
        },
      },
      getOutputDir: () => root,
      systemActions: {
        copy: async () => undefined,
        open: async () => { opens += 1; },
        reveal: async () => undefined,
      },
    });

    await expect(port.open({ preference: "transcript", videoId: video.videoId })).rejects.toThrow();
    expect(opens).toBe(0);
    expect(await readFile(victim, "utf8")).toBe("external victim");
  });
});
