import { spawnCommand, type SpawnCommand } from "../cli/system-actions";

export const FEEDBACK_EMAIL = "miguel.garglez@gmail.com";
export const GITHUB_ISSUES_URL = "https://github.com/miguelgarglez/video-digest/issues";

export type FeedbackOrigin = "failed-workflow" | "main-menu";

export type SupportContext = Readonly<{
  appVersion: string;
  architecture: string;
  macOSVersion: string;
}>;

export type FeedbackLinks = Readonly<{
  email: string;
  githubIssue: string;
}>;

type ContextInput = Readonly<{
  appVersion: string;
  architecture: string;
  run?: SpawnCommand;
}>;

export async function resolveSupportContext(input: ContextInput): Promise<SupportContext> {
  let macOSVersion = "unknown";
  try {
    const result = await (input.run ?? spawnCommand)(["/usr/bin/sw_vers", "-productVersion"]);
    const candidate = result.stdout.trim();
    if (result.exitCode === 0 && /^\d+(?:\.\d+){1,2}$/.test(candidate)) macOSVersion = candidate;
  } catch {
    // Support context is optional and must never block TUI startup.
  }

  return {
    appVersion: safeFact(input.appVersion),
    architecture: safeFact(input.architecture),
    macOSVersion,
  };
}

export function buildFeedbackLinks(context: SupportContext, origin: FeedbackOrigin): FeedbackLinks {
  const body = feedbackBody(context, origin);
  const email = `mailto:${FEEDBACK_EMAIL}?subject=${encodeURIComponent("Video Digest feedback")}` +
    `&body=${encodeURIComponent(body)}`;

  const githubIssue = new URL(`${GITHUB_ISSUES_URL}/new`);
  githubIssue.searchParams.set("title", "[Bug] ");
  githubIssue.searchParams.set("body", body);

  return { email, githubIssue: githubIssue.toString() };
}

function feedbackBody(context: SupportContext, origin: FeedbackOrigin): string {
  return [
    "What were you trying to do?",
    "",
    "What did you expect?",
    "",
    "What happened?",
    "",
    "Technical context (generated by Video Digest):",
    `- Video Digest: ${safeFact(context.appVersion)}`,
    `- macOS: ${safeFact(context.macOSVersion)}`,
    `- Architecture: ${safeFact(context.architecture)}`,
    `- Opened from: ${origin === "failed-workflow" ? "Failed workflow" : "Main menu"}`,
    "",
    "Do not include API keys, private artifacts, or sensitive paths.",
  ].join("\n");
}

function safeFact(value: string): string {
  const candidate = value.trim();
  return candidate.length > 0 && candidate.length <= 80 && !/[\r\n]/.test(candidate)
    ? candidate
    : "unknown";
}
