import type { Transcript } from "../transcript/transcript-source";
import type { YouTubeVideo } from "../video/youtube-url";

export type TranscriptDisplayMetadata = {
  channel?: string | null;
  title?: string | null;
};

export function renderTranscriptText(transcript: Transcript): string {
  const paragraphs: string[] = [];
  let current: string[] = [];
  let currentLength = 0;

  for (const segment of transcript.segments) {
    const text = segment.text.trim();
    if (!text) continue;

    current.push(text);
    currentLength += text.length + (current.length > 1 ? 1 : 0);

    if (currentLength >= 600 && /[.!?]$/.test(text)) {
      paragraphs.push(current.join(" "));
      current = [];
      currentLength = 0;
    }
  }

  if (current.length > 0) {
    paragraphs.push(current.join(" "));
  }

  return `${paragraphs.join("\n\n")}\n`;
}

export function formatTranscriptTimestamp(seconds: number): string {
  const totalSeconds = Number.isFinite(seconds) && seconds >= 0 ? Math.floor(seconds) : 0;
  const hours = Math.floor(totalSeconds / 3_600);
  const minutes = Math.floor((totalSeconds % 3_600) / 60);
  const remainingSeconds = totalSeconds % 60;
  const paddedMinutes = String(minutes).padStart(2, "0");
  const paddedSeconds = String(remainingSeconds).padStart(2, "0");

  return hours > 0
    ? `${hours}:${paddedMinutes}:${paddedSeconds}`
    : `${paddedMinutes}:${paddedSeconds}`;
}

export function renderTranscriptMarkdown(input: {
  metadata?: TranscriptDisplayMetadata;
  transcript: Transcript;
  video: YouTubeVideo;
}): string {
  const title = input.metadata?.title?.trim() || `Transcript ${input.video.videoId}`;
  const provenance = input.transcript.provenance.isAutoGenerated === null
    ? "unknown"
    : input.transcript.provenance.isAutoGenerated
      ? "auto-generated"
      : "manual";
  const lines = [
    `# ${title}`,
    "",
    `URL: ${input.video.canonicalUrl}`,
    `Language: ${input.transcript.language ?? "unknown"}`,
    `Source: ${input.transcript.source}`,
    `Provenance: ${provenance}`,
  ];

  const channel = input.metadata?.channel?.trim();
  if (channel) lines.push(`Channel: ${channel}`);

  lines.push("", "## Transcript", "");

  for (const segment of input.transcript.segments) {
    const text = segment.text.trim();
    if (!text) continue;
    lines.push(`**${formatTranscriptTimestamp(segment.start)}** ${text}`, "");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
