import { describe, expect, test } from "bun:test";
import type { Transcript } from "../transcript/transcript-source";
import type { YouTubeVideo } from "../video/youtube-url";
import {
  formatTranscriptTimestamp,
  renderTranscriptMarkdown,
  renderTranscriptText,
} from "./transcript-renderer";

describe("renderTranscriptText", () => {
  test("joins short segments into one readable paragraph", () => {
    expect(renderTranscriptText(transcriptWith("Hello", "world."))).toBe("Hello world.\n");
  });

  test("trims and omits empty segments", () => {
    expect(renderTranscriptText(transcriptWith("  Hello  ", "  ", "world.  "))).toBe(
      "Hello world.\n",
    );
  });

  test("splits a paragraph after 600 characters only at segment-ending punctuation", () => {
    const first = "a".repeat(599);
    const second = "continues";
    const third = "Done.";

    expect(renderTranscriptText(transcriptWith(first, second, third, "Next thought."))).toBe(
      `${first} ${second} ${third}\n\nNext thought.\n`,
    );
  });

  test("contains only transcript text, without timestamps or JSON keys", () => {
    const rendered = renderTranscriptText(transcriptWith("Canonical words."));

    expect(rendered).toBe("Canonical words.\n");
    expect(rendered).not.toContain("00:00");
    expect(rendered).not.toContain("segments");
    expect(rendered).not.toContain("schemaVersion");
  });
});

describe("formatTranscriptTimestamp", () => {
  test.each([
    [0, "00:00"],
    [59.9, "00:59"],
    [60, "01:00"],
    [3_599.9, "59:59"],
    [3_600, "1:00:00"],
    [3_661.8, "1:01:01"],
    [-1, "00:00"],
    [Number.NaN, "00:00"],
    [Number.POSITIVE_INFINITY, "00:00"],
  ])("formats %p seconds as %s", (seconds, expected) => {
    expect(formatTranscriptTimestamp(seconds as number)).toBe(expected);
  });
});

describe("renderTranscriptMarkdown", () => {
  test("renders display metadata and timestamped nonempty segments", () => {
    expect(
      renderTranscriptMarkdown({
        metadata: { channel: "Example Channel", title: "A useful video" },
        transcript: {
          ...transcriptWith(" First idea. ", " ", "Second idea."),
          language: "en",
          provenance: { isAutoGenerated: false },
          segments: [
            { duration: 5, start: 0, text: " First idea. " },
            { duration: 2, start: 5, text: " " },
            { duration: 5, start: 3_661.8, text: "Second idea." },
          ],
        },
        video,
      }),
    ).toBe(
      [
        "# A useful video",
        "",
        `URL: ${video.canonicalUrl}`,
        "Language: en",
        "Source: youtube-transcript-api",
        "Provenance: manual",
        "Channel: Example Channel",
        "",
        "## Transcript",
        "",
        "**00:00** First idea.",
        "",
        "**1:01:01** Second idea.",
        "",
      ].join("\n"),
    );
  });

  test("uses the video id fallback and labels unknown metadata", () => {
    const rendered = renderTranscriptMarkdown({
      transcript: { ...transcriptWith(), language: null, provenance: { isAutoGenerated: null } },
      video,
    });

    expect(rendered).toBe(
      [
        "# Transcript 1ZgUcrR0K7I",
        "",
        `URL: ${video.canonicalUrl}`,
        "Language: unknown",
        "Source: youtube-transcript-api",
        "Provenance: unknown",
        "",
        "## Transcript",
        "",
      ].join("\n"),
    );
  });
});

const video: YouTubeVideo = {
  canonicalUrl: "https://www.youtube.com/watch?v=1ZgUcrR0K7I",
  videoId: "1ZgUcrR0K7I",
};

function transcriptWith(...texts: string[]): Transcript {
  return {
    language: "en",
    provenance: { isAutoGenerated: true },
    schemaVersion: "transcript.v0",
    segments: texts.map((text, index) => ({ duration: 1, start: index, text })),
    source: "youtube-transcript-api",
    videoId: video.videoId,
  };
}
