import { homedir } from "node:os";
import { resolveAppPaths } from "../cli/app-paths";
import { resolvePackageResources } from "../cli/package-resources";
import { managedInterpreterPath } from "../cli/runtime-manager";
import type { YouTubeVideo } from "../video/youtube-url";
import {
  TranscriptSourceError,
  type Transcript,
  type TranscriptProvenance,
  type TranscriptSegment,
  type TranscriptSource,
} from "./transcript-source";

export type CommandResult = {
  exitCode: number;
  stderr: string;
  stdout: string;
};

export type CommandRunner = (command: string[], options: { cwd: string }) => Promise<CommandResult>;

export type PythonYoutubeTranscriptSourceOptions = {
  pythonDir?: string;
  runner?: CommandRunner;
  runtimePython?: string;
  sidecarScript?: string;
};

type SidecarTranscript = {
  language?: unknown;
  provenance?: unknown;
  segments?: unknown;
  source?: unknown;
  videoId?: unknown;
};

export class PythonYoutubeTranscriptSource implements TranscriptSource {
  private readonly pythonDir: string;
  private readonly runner: CommandRunner;
  private readonly runtimePython: string;
  private readonly sidecarScript: string;

  constructor(options: PythonYoutubeTranscriptSourceOptions = {}) {
    const resources = resolvePackageResources(import.meta.url);
    const runtimeDir = resolveAppPaths(homedir()).runtimeDir;
    this.pythonDir = options.pythonDir ?? resources.pythonDir;
    this.runner = options.runner ?? runCommand;
    this.runtimePython = options.runtimePython ?? managedInterpreterPath(runtimeDir);
    this.sidecarScript = options.sidecarScript ?? resources.sidecarScript;
  }

  async fetch(video: YouTubeVideo): Promise<Transcript> {
    const result = await this.runner(
      [this.runtimePython, this.sidecarScript, video.videoId],
      { cwd: this.pythonDir },
    );

    if (result.exitCode !== 0) {
      throw new TranscriptSourceError(
        result.exitCode === 2 ? "transcript-unavailable" : "provider-failed",
        result.stderr.trim() || `Transcript provider failed with exit code ${result.exitCode}`,
      );
    }

    return parseSidecarTranscript(result.stdout, video.videoId);
  }
}

function parseSidecarTranscript(stdout: string, expectedVideoId: string): Transcript {
  let payload: SidecarTranscript;

  try {
    payload = JSON.parse(stdout) as SidecarTranscript;
  } catch {
    throw new TranscriptSourceError("invalid-provider-response", "Transcript provider returned invalid JSON");
  }

  if (
    payload.videoId !== expectedVideoId ||
    payload.source !== "youtube-transcript-api" ||
    !Array.isArray(payload.segments)
  ) {
    throw new TranscriptSourceError("invalid-provider-response", "Transcript provider returned invalid shape");
  }

  return {
    language: typeof payload.language === "string" ? payload.language : null,
    provenance: parseProvenance(payload.provenance),
    schemaVersion: "transcript.v0",
    segments: payload.segments.map(parseSegment),
    source: "youtube-transcript-api",
    videoId: expectedVideoId,
  };
}

function parseProvenance(value: unknown): TranscriptProvenance {
  if (value === undefined || value === null) {
    return { isAutoGenerated: null };
  }

  if (!isRecord(value)) {
    throw new TranscriptSourceError("invalid-provider-response", "Transcript provider returned invalid provenance");
  }

  if (value.isAutoGenerated === undefined || value.isAutoGenerated === null) {
    return { isAutoGenerated: null };
  }

  if (typeof value.isAutoGenerated !== "boolean") {
    throw new TranscriptSourceError("invalid-provider-response", "Transcript provider returned invalid provenance");
  }

  return { isAutoGenerated: value.isAutoGenerated };
}

function parseSegment(segment: unknown): TranscriptSegment {
  if (!isRecord(segment) || typeof segment.start !== "number" || typeof segment.text !== "string") {
    throw new TranscriptSourceError("invalid-provider-response", "Transcript provider returned invalid segment");
  }

  return {
    duration: typeof segment.duration === "number" ? segment.duration : null,
    start: segment.start,
    text: segment.text,
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

async function runCommand(command: string[], options: { cwd: string }): Promise<CommandResult> {
  const process = Bun.spawn(command, {
    cwd: options.cwd,
    stderr: "pipe",
    stdout: "pipe",
  });

  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(process.stdout).text(),
    new Response(process.stderr).text(),
    process.exited,
  ]);

  return {
    exitCode,
    stderr,
    stdout,
  };
}
