import type { YouTubeVideo } from "../video/youtube-url";
import type { PublicCliErrorCode } from "../cli/public-contract";

export type TranscriptSegment = {
  duration: number | null;
  start: number;
  text: string;
};

export type TranscriptProvenance = {
  isAutoGenerated: boolean | null;
};

export type Transcript = {
  language: string | null;
  provenance: TranscriptProvenance;
  schemaVersion: "transcript.v0";
  segments: TranscriptSegment[];
  source: "youtube-transcript-api";
  videoId: string;
};

export type TranscriptSourceErrorCode = Extract<PublicCliErrorCode,
  | "provider-failed"
  | "transcript-unavailable"
  | "invalid-provider-response">;

export class TranscriptSourceError extends Error {
  constructor(
    public readonly code: TranscriptSourceErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "TranscriptSourceError";
  }
}

export type TranscriptSource = {
  fetch(video: YouTubeVideo, options?: { signal?: AbortSignal }): Promise<Transcript>;
};
