import { constants } from "node:fs";
import { lstat, mkdir, mkdtemp, open, readdir, realpath, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";
import {
  listLibraryEntries,
  revalidateLibraryOpenTarget,
  resolveLibraryEntry,
  type LibraryFileOperations,
} from "./artifacts";
import { writeTranscriptOnlyOutputs } from "../output/output-writer";

const VIDEO_ID = "1ZgUcrR0K7I";

describe("Artifact Library", () => {
  test("writes, lists, and resolves a Library Entry through a symlink root", async () => {
    const targetDir = await mkdtemp(join(tmpdir(), "video-digest-linked-target-"));
    const linkParent = await mkdtemp(join(tmpdir(), "video-digest-linked-parent-"));
    const outputDir = join(linkParent, "library");
    await symlink(targetDir, outputDir);

    await writeTranscriptOnlyOutputs({
      outputDir,
      transcript: {
        language: "en",
        provenance: { isAutoGenerated: null },
        schemaVersion: "transcript.v0",
        segments: [{ duration: 3, start: 0, text: "Linked library transcript." }],
        source: "youtube-transcript-api",
        videoId: VIDEO_ID,
      },
      transcriptQuality: {
        averageCharsPerMinute: 600,
        durationSeconds: 3,
        language: "en",
        qualitySchemaVersion: "transcript-quality.v0",
        segmentCount: 1,
        status: "warning",
        totalTextLength: 26,
        warnings: ["very-short-transcript"],
      },
      video: {
        canonicalUrl: `https://www.youtube.com/watch?v=${VIDEO_ID}`,
        videoId: VIDEO_ID,
      },
    });

    expect((await listLibraryEntries(outputDir)).map((entry) => entry.videoId)).toEqual([VIDEO_ID]);
    const resolved = await resolveLibraryEntry(outputDir, "latest");
    expect(resolved).toMatchObject({ ok: true, openPath: join(outputDir, "transcripts", `${VIDEO_ID}.md`) });
    if (!resolved.ok) throw new Error(resolved.message);
    await expect(revalidateLibraryOpenTarget(resolved.openTarget)).resolves.toBeUndefined();
  });

  test("lists a transcript-only entry from metadata with only available artifact paths", async () => {
    const outputDir = await createLibrary();
    await seedMetadata(outputDir, VIDEO_ID, {
      channel: "Example Channel",
      processedAt: "2026-06-18T12:00:00.000Z",
      title: "Example Video",
    });
    await writeArtifact(outputDir, "transcripts", `${VIDEO_ID}.json`, "{}\n");
    await writeArtifact(outputDir, "transcripts", `${VIDEO_ID}.md`, "# Transcript\n");
    await writeArtifact(outputDir, "transcripts", `${VIDEO_ID}.txt`, "Transcript\n");

    expect(await listLibraryEntries(outputDir)).toEqual([
      {
        channel: "Example Channel",
        paths: {
          digestPath: null,
          emailPreviewPath: null,
          metadataPath: join(outputDir, "metadata", `${VIDEO_ID}.json`),
          transcriptJsonPath: join(outputDir, "transcripts", `${VIDEO_ID}.json`),
          transcriptMarkdownPath: join(outputDir, "transcripts", `${VIDEO_ID}.md`),
          transcriptTextPath: join(outputDir, "transcripts", `${VIDEO_ID}.txt`),
        },
        title: "Example Video",
        updatedAt: "2026-06-18T12:00:00.000Z",
        videoId: VIDEO_ID,
      },
    ]);
  });

  test("sorts by processedAt descending with a deterministic video ID tie-break", async () => {
    const outputDir = await createLibrary();
    for (const [videoId, processedAt] of [
      ["BBBBBBBBBBB", "2026-06-18T12:00:00.000Z"],
      ["AAAAAAAAAAA", "2026-06-18T12:00:00.000Z"],
      ["CCCCCCCCCCC", "2026-06-19T12:00:00.000Z"],
    ] as const) {
      await seedMetadata(outputDir, videoId, { processedAt });
      await writeArtifact(outputDir, "transcripts", `${videoId}.md`, "# Transcript\n");
    }

    expect((await listLibraryEntries(outputDir)).map((entry) => entry.videoId)).toEqual([
      "CCCCCCCCCCC",
      "AAAAAAAAAAA",
      "BBBBBBBBBBB",
    ]);
  });

  test("opens a digest before transcript Markdown and falls back to transcript Markdown", async () => {
    const outputDir = await createLibrary();
    await seedMetadata(outputDir, VIDEO_ID, { processedAt: "2026-06-18T12:00:00.000Z" });
    await writeArtifact(outputDir, "digests", `${VIDEO_ID}.md`, "# Digest\n");
    await writeArtifact(outputDir, "transcripts", `${VIDEO_ID}.md`, "# Transcript\n");

    const digestResult = await resolveLibraryEntry(outputDir, "latest");
    expect(digestResult).toMatchObject({
      ok: true,
      openPath: join(outputDir, "digests", `${VIDEO_ID}.md`),
    });

    const transcriptOnlyDir = await createLibrary();
    await seedMetadata(transcriptOnlyDir, VIDEO_ID, { processedAt: "2026-06-18T12:00:00.000Z" });
    await writeArtifact(transcriptOnlyDir, "transcripts", `${VIDEO_ID}.md`, "# Transcript\n");

    expect(await resolveLibraryEntry(transcriptOnlyDir, VIDEO_ID)).toMatchObject({
      ok: true,
      openPath: join(transcriptOnlyDir, "transcripts", `${VIDEO_ID}.md`),
    });
  });

  test("skips malformed, mismatched, and symlinked metadata without following external files", async () => {
    const outputDir = await createLibrary();
    const externalDir = await mkdtemp(join(tmpdir(), "video-digest-external-"));
    const externalMetadata = join(externalDir, `${VIDEO_ID}.json`);
    await writeFile(externalMetadata, JSON.stringify(metadata(VIDEO_ID, { processedAt: "2026-06-18T12:00:00.000Z" })));
    await writeFile(join(outputDir, "metadata", "AAAAAAAAAAA.json"), "not-json");
    await writeFile(
      join(outputDir, "metadata", "BBBBBBBBBBB.json"),
      JSON.stringify(metadata("CCCCCCCCCCC", { processedAt: "2026-06-18T12:00:00.000Z" })),
    );
    await symlink(externalMetadata, join(outputDir, "metadata", `${VIDEO_ID}.json`));
    await writeArtifact(outputDir, "transcripts", `${VIDEO_ID}.md`, "# External transcript candidate\n");

    expect(await listLibraryEntries(outputDir)).toEqual([]);
  });

  test.each(["EACCES", "EIO", "EMFILE"])("propagates %s while reading the metadata directory", async (code) => {
    const outputDir = await createLibrary();
    const operations = libraryOperations({
      readdir: async () => { throw nodeError(code); },
    });

    await expect(listLibraryEntries(outputDir, operations)).rejects.toMatchObject({ code });
  });

  test("propagates metadata open, read, and stat failures instead of returning an empty library", async () => {
    const outputDir = await createLibrary();
    await seedMetadata(outputDir, VIDEO_ID, { processedAt: "2026-06-18T12:00:00.000Z" });

    for (const operation of ["open", "read", "stat"] as const) {
      const error = nodeError("EACCES");
      const operations = libraryOperations(operation === "open"
        ? { open: async () => { throw error; } }
        : operation === "stat"
          ? { lstat: async (path) => {
            if (path.endsWith(`${VIDEO_ID}.json`)) throw error;
            return lstat(path);
          } }
          : { open: async (path, flags) => {
            const handle = await open(path, flags);
            return {
              close: () => handle.close(),
              readFile: async () => { throw error; },
              stat: () => handle.stat(),
            };
          } });

      await expect(listLibraryEntries(outputDir, operations)).rejects.toBe(error);
    }
  });

  test("distinguishes an absent entry from an entry with no readable artifact", async () => {
    const outputDir = await createLibrary();
    await seedMetadata(outputDir, VIDEO_ID, { processedAt: "2026-06-18T12:00:00.000Z" });

    expect(await resolveLibraryEntry(outputDir, "AAAAAAAAAAA")).toMatchObject({
      errorCode: "library-entry-not-found",
      ok: false,
    });
    expect(await resolveLibraryEntry(outputDir, VIDEO_ID)).toMatchObject({
      errorCode: "library-entry-not-openable",
      message: expect.stringContaining("Reprocess"),
      ok: false,
    });
  });

  test("checks metadata file identity before reading through its already-open handle", async () => {
    const outputDir = await createLibrary();
    await seedMetadata(outputDir, VIDEO_ID, { processedAt: "2026-06-18T12:00:00.000Z" });
    let externalRead = false;
    let openFlags = 0;
    const operations = libraryOperations({
      open: async (_path, flags) => {
        openFlags = flags;
        return {
          close: async () => {},
          readFile: async () => { externalRead = true; return "{}"; },
          stat: async () => fileStats({ dev: 900, ino: 901 }),
        };
      },
    });

    await expect(listLibraryEntries(outputDir, operations)).rejects.toThrow("changed during validation");
    expect(externalRead).toBe(false);
    expect(openFlags & constants.O_RDONLY).toBe(constants.O_RDONLY);
    if (constants.O_NOFOLLOW !== undefined) {
      expect(openFlags & constants.O_NOFOLLOW).toBe(constants.O_NOFOLLOW);
    }
  });

  test("revalidates an artifact identity immediately before returning it", async () => {
    const outputDir = await createLibrary();
    await seedMetadata(outputDir, VIDEO_ID, { processedAt: "2026-06-18T12:00:00.000Z" });
    const digestPath = await writeArtifact(outputDir, "digests", `${VIDEO_ID}.md`, "# Digest\n");
    let digestStats = 0;
    const operations = libraryOperations({
      lstat: async (path) => {
        const stats = await lstat(path);
        if (path === digestPath && ++digestStats === 2) {
          return fileStats({ dev: stats.dev, ino: stats.ino + 1 });
        }
        return stats;
      },
    });

    await expect(listLibraryEntries(outputDir, operations)).rejects.toThrow("changed during validation");
  });

  test("fails closed before metadata read when the Library root inode is replaced", async () => {
    const outputDir = await createLibrary();
    await seedMetadata(outputDir, VIDEO_ID, { processedAt: "2026-06-18T12:00:00.000Z" });
    let rootLstats = 0;
    let metadataOpened = false;
    const operations = libraryOperations({
      lstat: async (path) => {
        const stats = await lstat(path);
        if (path === outputDir && ++rootLstats >= 2) {
          return directoryStats({ dev: stats.dev, ino: stats.ino + 1 });
        }
        return stats;
      },
      open: async (path, flags) => {
        metadataOpened = true;
        return open(path, flags);
      },
    });

    await expect(listLibraryEntries(outputDir, operations)).rejects.toThrow("changed during validation");
    expect(metadataOpened).toBe(false);
  });
});

async function createLibrary(): Promise<string> {
  const outputDir = await mkdtemp(join(tmpdir(), "video-digest-library-"));
  await mkdir(join(outputDir, "metadata"), { recursive: true });
  return outputDir;
}

async function seedMetadata(
  outputDir: string,
  videoId: string,
  input: { channel?: string | null; processedAt: string; title?: string | null },
): Promise<void> {
  await writeFile(
    join(outputDir, "metadata", `${videoId}.json`),
    `${JSON.stringify(metadata(videoId, input), null, 2)}\n`,
  );
}

function metadata(
  videoId: string,
  input: { channel?: string | null; processedAt: string; title?: string | null },
) {
  return {
    digest: null,
    generation: null,
    metadataSchemaVersion: "metadata.v1",
    mode: "transcript-only",
    processedAt: input.processedAt,
    transcriptQuality: {},
    video: {
      canonicalUrl: `https://www.youtube.com/watch?v=${videoId}`,
      channel: input.channel ?? null,
      durationSeconds: 60,
      videoId,
      videoTitle: input.title ?? null,
    },
    videoDigestVersion: "0.2.0",
  };
}

async function writeArtifact(outputDir: string, directory: string, name: string, contents: string): Promise<string> {
  await mkdir(join(outputDir, directory), { recursive: true });
  const path = join(outputDir, directory, name);
  await writeFile(path, contents);
  return path;
}

function libraryOperations(overrides: Partial<LibraryFileOperations> = {}) {
  return {
    lstat,
    open,
    readdir,
    realpath,
    ...overrides,
  } as never;
}

function nodeError(code: string): NodeJS.ErrnoException {
  return Object.assign(new Error(code), { code });
}

function fileStats(identity: { dev: number; ino: number }) {
  return {
    ...identity,
    isDirectory: () => false,
    isFile: () => true,
    isSymbolicLink: () => false,
    mode: constants.S_IFREG,
  } as never;
}

function directoryStats(identity: { dev: number; ino: number }) {
  return {
    ...identity,
    isDirectory: () => true,
    isFile: () => false,
    isSymbolicLink: () => false,
  } as never;
}
