import { describe, expect, test } from "bun:test";
import { AnthropicMessagesSummarizer } from "./anthropic-messages-summarizer";
import { digestJsonSchema } from "./digest-request";
import type { FetchLike } from "./http";
import { getProviderProfile } from "./providers";
import type { SummarizerInput } from "./summarizer";

describe("AnthropicMessagesSummarizer", () => {
  test("uses native Messages structured output and normalizes provenance", async () => {
    let request: { init?: RequestInit; url?: string } = {};
    const fetch: FetchLike = async (url, init) => {
      request = { init, url: String(url) };
      return Response.json({
        content: [{ text: JSON.stringify(digestDraft()), type: "text" }],
        id: "msg_123",
        model: "claude-sonnet-4-6",
        usage: { input_tokens: 100, output_tokens: 20 },
      });
    };
    const profile = getProviderProfile("anthropic");
    const summarizer = new AnthropicMessagesSummarizer({
      apiKey: "test-key", fetch, model: profile.defaultModel, profile,
    });

    const result = await summarizer.generateDigest(input());

    expect(request.url).toBe("https://api.anthropic.com/v1/messages");
    expect(request.init?.headers).toEqual({
      "Content-Type": "application/json",
      "anthropic-version": "2023-06-01",
      "x-api-key": "test-key",
    });
    expect(JSON.parse(String(request.init?.body))).toEqual({
      max_tokens: 4096,
      messages: [{ content: expect.any(String), role: "user" }],
      model: "claude-sonnet-4-6",
      output_config: { format: { schema: digestJsonSchema(), type: "json_schema" } },
      system: expect.any(String),
    });
    expect(result).toEqual({
      draft: digestDraft(),
      generation: {
        provider: "anthropic",
        requestId: "msg_123",
        requestedModel: "claude-sonnet-4-6",
        responseModel: "claude-sonnet-4-6",
        usage: { inputTokens: 100, outputTokens: 20, totalTokens: 120 },
      },
    });
  });

  test("rejects non-text content safely", async () => {
    const profile = getProviderProfile("anthropic");
    const summarizer = new AnthropicMessagesSummarizer({
      apiKey: "test-key",
      fetch: async () => Response.json({ content: [{ type: "thinking" }] }),
      model: profile.defaultModel,
      profile,
    });
    await expect(summarizer.generateDigest(input())).rejects.toMatchObject({
      code: "invalid-provider-response",
      provider: "anthropic",
    });
  });
});

function input(): SummarizerInput {
  return {
    transcript: { language: "en", provenance: { isAutoGenerated: null }, schemaVersion: "transcript.v0", segments: [{ duration: 5, start: 0, text: "Opening statement" }], source: "youtube-transcript-api", videoId: "1ZgUcrR0K7I" },
    transcriptQuality: { averageCharsPerMinute: 720, durationSeconds: 5, language: "en", qualitySchemaVersion: "transcript-quality.v0", segmentCount: 1, status: "warning", totalTextLength: 17, warnings: ["low-segment-count"] },
    video: { canonicalUrl: "https://www.youtube.com/watch?v=1ZgUcrR0K7I", videoId: "1ZgUcrR0K7I" },
  };
}

function digestDraft() {
  return { actionableIdeas: ["Act"], conceptsToInvestigate: ["Concept"], connections: ["Connection"], digestTitle: "Title", keyIdeas: ["Idea"], relevantTimestamps: [{ note: "Opening", timestamp: "0:00" }], tldr: ["Summary"], verdict: "watch_fragments" as const };
}
