import { describe, expect, test } from "bun:test";
import { digestJsonSchema } from "./digest-request";
import type { FetchLike } from "./http";
import { getProviderProfile } from "./providers";
import { ChatCompletionsSummarizer } from "./chat-completions-summarizer";
import type { SummarizerInput } from "./summarizer";

describe("ChatCompletionsSummarizer", () => {
  test("uses Gemini's OpenAI-compatible Chat Completions contract", async () => {
    let request: { init?: RequestInit; url?: string } = {};
    const fetch: FetchLike = async (url, init) => {
      request = { init, url: String(url) };
      return Response.json({
        choices: [{ message: { content: JSON.stringify(digestDraft()), role: "assistant" } }],
        id: "chatcmpl_123",
        model: "gemini-3.5-flash",
        usage: { completion_tokens: 20, prompt_tokens: 100, total_tokens: 120 },
      });
    };
    const profile = getProviderProfile("gemini");
    const summarizer = new ChatCompletionsSummarizer({
      apiKey: "test-key",
      fetch,
      model: profile.defaultModel,
      profile,
    });

    const result = await summarizer.generateDigest(input());

    expect(request.url).toBe(profile.endpoint);
    expect(request.init?.headers).toEqual({
      Authorization: "Bearer test-key",
      "Content-Type": "application/json",
    });
    expect(JSON.parse(String(request.init?.body))).toEqual({
      messages: [
        { content: expect.any(String), role: "system" },
        { content: expect.any(String), role: "user" },
      ],
      model: "gemini-3.5-flash",
      response_format: {
        json_schema: {
          name: "digest_draft",
          schema: digestJsonSchema(),
          strict: true,
        },
        type: "json_schema",
      },
    });
    expect(result).toEqual({
      draft: digestDraft(),
      generation: {
        provider: "gemini",
        requestId: "chatcmpl_123",
        requestedModel: "gemini-3.5-flash",
        responseModel: "gemini-3.5-flash",
        usage: { inputTokens: 100, outputTokens: 20, totalTokens: 120 },
      },
    });
  });

  test("rejects missing assistant content and reflected failures safely", async () => {
    const profile = getProviderProfile("gemini");
    const malformed = new ChatCompletionsSummarizer({
      apiKey: "test-key",
      fetch: async () => Response.json({ choices: [] }),
      model: profile.defaultModel,
      profile,
    });
    await expect(malformed.generateDigest(input())).rejects.toMatchObject({
      code: "invalid-provider-response",
      provider: "gemini",
    });

    const reflected = new ChatCompletionsSummarizer({
      apiKey: "test-key",
      fetch: async () => new Response("Bearer test-key", { status: 401 }),
      model: profile.defaultModel,
      profile,
    });
    const failure = reflected.generateDigest(input());
    await expect(failure).rejects.toMatchObject({ code: "authentication-failed" });
    await expect(failure).rejects.not.toThrow("test-key");
  });
});

function input(): SummarizerInput {
  return {
    transcript: {
      language: "en",
      provenance: { isAutoGenerated: null },
      schemaVersion: "transcript.v0",
      segments: [{ duration: 5, start: 0, text: "Opening statement" }],
      source: "youtube-transcript-api",
      videoId: "1ZgUcrR0K7I",
    },
    transcriptQuality: {
      averageCharsPerMinute: 720,
      durationSeconds: 5,
      language: "en",
      qualitySchemaVersion: "transcript-quality.v0",
      segmentCount: 1,
      status: "warning",
      totalTextLength: 17,
      warnings: ["low-segment-count"],
    },
    video: { canonicalUrl: "https://www.youtube.com/watch?v=1ZgUcrR0K7I", videoId: "1ZgUcrR0K7I" },
  };
}

function digestDraft() {
  return {
    actionableIdeas: ["Act"], conceptsToInvestigate: ["Concept"], connections: ["Connection"],
    digestTitle: "Title", keyIdeas: ["Idea"],
    relevantTimestamps: [{ note: "Opening", timestamp: "0:00" }],
    tldr: ["Summary"], verdict: "watch_fragments" as const,
  };
}
