import { describe, expect, test } from "bun:test";
import {
  buildDigestSystemPrompt,
  buildDigestUserPrompt,
  digestJsonSchema,
  parseDigestDraft,
} from "./digest-request";
import type { SummarizerInput } from "./summarizer";

const draft = {
  actionableIdeas: ["Act"],
  conceptsToInvestigate: ["Concept"],
  connections: ["Connection"],
  digestTitle: "Title",
  keyIdeas: ["Idea"],
  relevantTimestamps: [{ note: "Opening", timestamp: "0:00" }],
  tldr: ["Summary"],
  verdict: "watch_fragments" as const,
};

describe("Digest request contract", () => {
  test("builds one shared prompt for every provider", () => {
    expect(buildDigestSystemPrompt()).toContain("structured personal knowledge digests");
    expect(buildDigestUserPrompt(input())).toContain("00:00 Opening statement");
  });

  test("defines the complete strict Digest schema", () => {
    expect(digestJsonSchema()).toMatchObject({
      additionalProperties: false,
      required: [
        "digestTitle",
        "tldr",
        "keyIdeas",
        "relevantTimestamps",
        "actionableIdeas",
        "conceptsToInvestigate",
        "connections",
        "verdict",
      ],
      type: "object",
    });
  });

  test("parses a valid draft and rejects invalid provider output", () => {
    expect(parseDigestDraft(JSON.stringify(draft))).toEqual(draft);
    expect(() => parseDigestDraft("{}"))
      .toThrow("Provider output did not match digest.v0 draft");
    expect(() => parseDigestDraft("not-json"))
      .toThrow("Provider output was not valid JSON");
  });
});

function input(): SummarizerInput {
  return {
    transcript: {
      language: "en",
      provenance: { isAutoGenerated: null },
      schemaVersion: "transcript.v0",
      segments: [{ duration: 5, start: 0, text: "Opening statement" }],
      source: "youtube-transcript-api",
      videoId: "1ZgUcrR0K7I",
    },
    transcriptQuality: {
      averageCharsPerMinute: 720,
      durationSeconds: 5,
      language: "en",
      qualitySchemaVersion: "transcript-quality.v0",
      segmentCount: 1,
      status: "warning",
      totalTextLength: 17,
      warnings: ["low-segment-count"],
    },
    video: {
      canonicalUrl: "https://www.youtube.com/watch?v=1ZgUcrR0K7I",
      videoId: "1ZgUcrR0K7I",
    },
  };
}
