import json
import os
import sys

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.proxies import GenericProxyConfig, WebshareProxyConfig

TRANSCRIPT_LANGUAGES = ("en", "es")


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: fetch_transcript.py <video-id>", file=sys.stderr)
        return 1

    video_id = sys.argv[1]

    try:
        transcript = YouTubeTranscriptApi(proxy_config=proxy_config()).fetch(
            video_id,
            languages=TRANSCRIPT_LANGUAGES,
        )
    except Exception as error:
        print(str(error), file=sys.stderr)
        return 2

    payload = {
        "language": getattr(transcript, "language_code", None),
        "provenance": {
            "isAutoGenerated": optional_bool_attr(
                transcript,
                ("is_generated", "is_auto_generated", "is_auto_generated_transcript"),
            )
        },
        "segments": [
            {
                "duration": snippet.duration,
                "start": snippet.start,
                "text": snippet.text,
            }
            for snippet in transcript
        ],
        "source": "youtube-transcript-api",
        "videoId": video_id,
    }

    print(json.dumps(payload, ensure_ascii=False))
    return 0


def proxy_config():
    webshare_username = os.getenv("YOUTUBE_TRANSCRIPT_WEBSHARE_USERNAME")
    webshare_password = os.getenv("YOUTUBE_TRANSCRIPT_WEBSHARE_PASSWORD")
    if webshare_username and webshare_password:
        locations = [
            location.strip()
            for location in os.getenv("YOUTUBE_TRANSCRIPT_WEBSHARE_LOCATIONS", "").split(",")
            if location.strip()
        ]
        kwargs = {
            "proxy_username": webshare_username,
            "proxy_password": webshare_password,
        }
        if locations:
            kwargs["filter_ip_locations"] = locations
        return WebshareProxyConfig(**kwargs)

    http_url = os.getenv("YOUTUBE_TRANSCRIPT_PROXY_HTTP_URL")
    https_url = os.getenv("YOUTUBE_TRANSCRIPT_PROXY_HTTPS_URL")
    if http_url or https_url:
        return GenericProxyConfig(http_url=http_url, https_url=https_url)

    return None


def optional_bool_attr(source, names):
    for name in names:
        value = getattr(source, name, None)
        if callable(value):
            value = value()
        if isinstance(value, bool):
            return value

    return None


if __name__ == "__main__":
    raise SystemExit(main())
