import json
import sys

from youtube_transcript_api import YouTubeTranscriptApi

TRANSCRIPT_LANGUAGES = ("en", "es")


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: fetch_transcript.py <video-id>", file=sys.stderr)
        return 1

    video_id = sys.argv[1]

    try:
        transcript = YouTubeTranscriptApi().fetch(video_id, languages=TRANSCRIPT_LANGUAGES)
    except Exception as error:
        print(str(error), file=sys.stderr)
        return 2

    payload = {
        "language": getattr(transcript, "language_code", None),
        "provenance": {
            "isAutoGenerated": optional_bool_attr(
                transcript,
                ("is_generated", "is_auto_generated", "is_auto_generated_transcript"),
            )
        },
        "segments": [
            {
                "duration": snippet.duration,
                "start": snippet.start,
                "text": snippet.text,
            }
            for snippet in transcript
        ],
        "source": "youtube-transcript-api",
        "videoId": video_id,
    }

    print(json.dumps(payload, ensure_ascii=False))
    return 0


def optional_bool_attr(source, names):
    for name in names:
        value = getattr(source, name, None)
        if callable(value):
            value = value()
        if isinstance(value, bool):
            return value

    return None


if __name__ == "__main__":
    raise SystemExit(main())
