import { resolveProviderApiKey } from "../src/cli/credentials";
import { createProviderSummarizer } from "../src/summarizer/provider-summarizer";
import { AnthropicMessagesSummarizer } from "../src/summarizer/anthropic-messages-summarizer";
import { ChatCompletionsSummarizer } from "../src/summarizer/chat-completions-summarizer";
import { ResponsesSummarizer } from "../src/summarizer/responses-summarizer";
import { getProviderProfile, isDigestProviderId, type DigestProviderId, type ProviderProtocol } from "../src/summarizer/providers";
import type { Summarizer } from "../src/summarizer/summarizer";
import { VIDEO_DIGEST_VERSION } from "../src/version";

type ZenProtocol = ProviderProtocol;
type LiveArgs = { ok: true; provider: DigestProviderId; zenProtocol: ZenProtocol | null } | { message: string; ok: false };

const zenTargets = {
  responses: { endpoint: "https://opencode.ai/zen/v1/responses", model: "gpt-5.4-mini" },
  "anthropic-messages": { endpoint: "https://opencode.ai/zen/v1/messages", model: "claude-haiku-4-5" },
  "chat-completions": { endpoint: "https://opencode.ai/zen/v1/chat/completions", model: "deepseek-v4-flash" },
} as const;

export function parseLiveArgs(args: string[]): LiveArgs {
  const providerIndex = args.indexOf("--provider");
  const provider = providerIndex >= 0 ? args[providerIndex + 1] : undefined;
  if (!provider || !isDigestProviderId(provider)) return { message: "Use --provider with a supported provider ID.", ok: false };
  if (!args.includes("--yes")) return { message: "Live verification requires --yes after reviewing its request scope.", ok: false };
  const zenIndex = args.indexOf("--zen-protocol");
  const zenProtocol = zenIndex >= 0 ? args[zenIndex + 1] : null;
  if (zenProtocol !== null && (zenProtocol === undefined || !(zenProtocol in zenTargets) || provider !== "opencode")) {
    return { message: "--zen-protocol is only supported with provider opencode.", ok: false };
  }
  return { ok: true, provider, zenProtocol: zenProtocol as ZenProtocol | null };
}

export function redactLiveReport<T extends Record<string, unknown>>(report: T): Omit<T, "requestId" | "usage"> {
  const { requestId: _requestId, usage: _usage, ...safe } = report;
  return safe;
}

if (import.meta.main) {
  const parsed = parseLiveArgs(Bun.argv.slice(2));
  if (!parsed.ok) { console.error(parsed.message); process.exit(1); }
  const base = getProviderProfile(parsed.provider);
  const target = parsed.zenProtocol
    ? zenTargets[parsed.zenProtocol]
    : { endpoint: base.endpoint, model: base.defaultModel };
  console.error(`Provider: ${base.displayName}\nEndpoint: ${target.endpoint}\nModel: ${target.model}\nScope: one small synthetic Digest request.`);
  const credential = await resolveProviderApiKey({
    env: process.env,
    provider: parsed.provider,
    store: { deleteApiKey: async () => {}, getApiKey: async () => null, setApiKey: async () => {} },
  });
  if (!credential.value) { console.error(JSON.stringify({ code: "missing-api-key", model: target.model, provider: parsed.provider })); process.exit(1); }
  const summarizer = createLiveSummarizer(parsed, credential.value);
  try {
    await summarizer.generateDigest({
      transcript: { language: "en", provenance: { isAutoGenerated: false }, schemaVersion: "transcript.v0", segments: [{ duration: 2, start: 0, text: "A concise software engineering lesson about reliable interfaces." }], source: "youtube-transcript-api", videoId: "live-test-1" },
      transcriptQuality: { averageCharsPerMinute: 900, durationSeconds: 2, language: "en", qualitySchemaVersion: "transcript-quality.v0", segmentCount: 1, status: "usable", totalTextLength: 64, warnings: [] },
      video: { canonicalUrl: "https://www.youtube.com/watch?v=live-test-1", videoId: "live-test-1" },
    });
    console.log(JSON.stringify({ model: target.model, provider: parsed.provider, status: "passed", timestamp: new Date().toISOString(), videoDigestVersion: VIDEO_DIGEST_VERSION }));
  } catch (error) {
    const code = error instanceof Error && "code" in error ? String(error.code) : "provider-failed";
    console.error(JSON.stringify({ code, model: target.model, provider: parsed.provider }));
    process.exit(1);
  }
}

function createLiveSummarizer(parsed: Extract<LiveArgs, { ok: true }>, apiKey: string): Summarizer {
  if (!parsed.zenProtocol) {
    const profile = getProviderProfile(parsed.provider);
    return createProviderSummarizer({ model: { effective: profile.defaultModel, source: "default" }, provider: { effective: parsed.provider, source: "flag" } }, apiKey);
  }
  const target = zenTargets[parsed.zenProtocol];
  const profile = { ...getProviderProfile("opencode"), ...target, protocol: parsed.zenProtocol };
  const options = { apiKey, model: target.model, profile };
  switch (parsed.zenProtocol) {
    case "responses": return new ResponsesSummarizer(options);
    case "anthropic-messages": return new AnthropicMessagesSummarizer(options);
    case "chat-completions": return new ChatCompletionsSummarizer(options);
  }
}
