import { mkdtemp, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, test } from "bun:test";
import { fetchTranscriptOnly } from "./transcript-only";
import type { Transcript } from "../transcript/transcript-source";

describe("fetchTranscriptOnly", () => {
  test("fetches transcript, scores quality, and writes transcript artifacts", async () => {
    const outputDir = await mkdtemp(join(tmpdir(), "video-digest-transcript-only-"));
    const progressStages: string[] = [];

    const result = await fetchTranscriptOnly({
      onProgress: (event) => progressStages.push(event.stage),
      outputDir,
      transcriptSource: {
        fetch: async () => transcript,
      },
      video: {
        canonicalUrl: "https://www.youtube.com/watch?v=1ZgUcrR0K7I",
        videoId: "1ZgUcrR0K7I",
      },
    });

    expect(result).toEqual({
      cleanText: expect.any(String),
      exitCode: 0,
      paths: {
        metadataPath: join(outputDir, "metadata", "1ZgUcrR0K7I.json"),
        transcriptJsonPath: join(outputDir, "transcripts", "1ZgUcrR0K7I.json"),
        transcriptMarkdownPath: join(outputDir, "transcripts", "1ZgUcrR0K7I.md"),
        transcriptTextPath: join(outputDir, "transcripts", "1ZgUcrR0K7I.txt"),
      },
      status: "completed",
      transcriptQuality: expect.objectContaining({
        status: "usable",
      }),
    });
    expect(progressStages).toEqual(["fetching-transcript", "scoring-transcript", "writing-outputs", "completed"]);
    expect(await readFile(result.paths.transcriptJsonPath, "utf8")).toContain("transcript.v0");
    expect(await readFile(result.paths.transcriptMarkdownPath, "utf8")).toContain(
      "**00:00** This is a substantial transcript segment with useful content.",
    );
    expect(await readFile(result.paths.transcriptTextPath, "utf8")).toContain(
      "This is a substantial transcript segment with useful content.",
    );
    expect(result.cleanText).toBe(await readFile(result.paths.transcriptTextPath, "utf8"));
  });

  test("persists one best-effort metadata lookup in JSON and Markdown", async () => {
    const outputDir = await mkdtemp(join(tmpdir(), "video-digest-transcript-only-"));
    let metadataCalls = 0;

    const result = await fetchTranscriptOnly({
      metadataSource: {
        async fetch() {
          metadataCalls += 1;
          return { channel: "A channel", title: "A title" };
        },
      },
      outputDir,
      transcriptSource: { fetch: async () => transcript },
      video,
    });

    expect(metadataCalls).toBe(1);
    expect(JSON.parse(await readFile(result.paths.metadataPath, "utf8"))).toMatchObject({
      video: { channel: "A channel", videoTitle: "A title" },
    });
    expect(await readFile(result.paths.transcriptMarkdownPath, "utf8")).toContain(
      "# A title\n\nURL: https://www.youtube.com/watch?v=1ZgUcrR0K7I",
    );
    expect(await readFile(result.paths.transcriptMarkdownPath, "utf8")).toContain("Channel: A channel");
  });

  test("continues with null metadata when lookup fails", async () => {
    const outputDir = await mkdtemp(join(tmpdir(), "video-digest-transcript-only-"));

    const result = await fetchTranscriptOnly({
      metadataSource: {
        async fetch() {
          throw new Error("offline");
        },
      },
      outputDir,
      transcriptSource: { fetch: async () => transcript },
      video,
    });

    expect(result.exitCode).toBe(0);
    expect(JSON.parse(await readFile(result.paths.metadataPath, "utf8"))).toMatchObject({
      video: { channel: null, videoTitle: null },
    });
  });
});

const video = {
  canonicalUrl: "https://www.youtube.com/watch?v=1ZgUcrR0K7I",
  videoId: "1ZgUcrR0K7I",
};

const transcript: Transcript = {
  language: "en",
  provenance: { isAutoGenerated: false },
  schemaVersion: "transcript.v0",
  segments: Array.from({ length: 60 }, (_, index) => ({
    duration: 10,
    start: index * 10,
    text: "This is a substantial transcript segment with useful content.",
  })),
  source: "youtube-transcript-api",
  videoId: "1ZgUcrR0K7I",
};
