import { mkdtemp, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, test } from "bun:test";
import { fetchTranscriptOnly } from "./transcript-only";
import type { Transcript } from "../transcript/transcript-source";

describe("fetchTranscriptOnly", () => {
  test("fetches transcript, scores quality, and writes transcript artifacts", async () => {
    const outputDir = await mkdtemp(join(tmpdir(), "video-digest-transcript-only-"));
    const progressStages: string[] = [];

    const result = await fetchTranscriptOnly({
      onProgress: (event) => progressStages.push(event.stage),
      outputDir,
      transcriptSource: {
        fetch: async () => transcript,
      },
      video: {
        canonicalUrl: "https://www.youtube.com/watch?v=1ZgUcrR0K7I",
        videoId: "1ZgUcrR0K7I",
      },
    });

    expect(result).toEqual({
      exitCode: 0,
      paths: {
        metadataPath: join(outputDir, "metadata", "1ZgUcrR0K7I.json"),
        transcriptPath: join(outputDir, "transcripts", "1ZgUcrR0K7I.json"),
      },
      status: "completed",
      transcriptQuality: expect.objectContaining({
        status: "usable",
      }),
    });
    expect(progressStages).toEqual(["fetching-transcript", "scoring-transcript", "writing-outputs", "completed"]);
    expect(await readFile(result.paths.transcriptPath, "utf8")).toContain("transcript.v0");
  });
});

const transcript: Transcript = {
  language: "en",
  provenance: { isAutoGenerated: false },
  schemaVersion: "transcript.v0",
  segments: Array.from({ length: 60 }, (_, index) => ({
    duration: 10,
    start: index * 10,
    text: "This is a substantial transcript segment with useful content.",
  })),
  source: "youtube-transcript-api",
  videoId: "1ZgUcrR0K7I",
};
